apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluedeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mywebapp
      version: blue
  template:
    metadata:
      labels:
        app: mywebapp
        version: blue
    spec:
      containers:
      - name: webapp
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-blue
          mountPath: /usr/share/nginx/html
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: nginx-blue
        configMap:
          name: configmapblue
