apiVersion: v1
kind: Service
metadata:
  name: bluegreenservice
spec:
  selector:
    app: mywebapp
    version: blue  # on green pour lancer la page green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
